# Generated by Django 5.2.7 on 2025-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='private_user_info',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
