# Generated by Django 5.2.7 on 2025-11-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_de_servicos',
            name='servico_nome',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tipos_de_servicos',
            name='tempo_duracao',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
