# Generated by Django 5.2.7 on 2026-01-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_tipos_de_servicos_servico_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dias_ocupados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_ocupado_inteiro', models.DateField()),
                ('dia_ocupado_metade_inicio', models.DateTimeField()),
                ('dia_ocupado_metade_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='horario_de_desligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_sempre_ocupado', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='horarios_agendados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.TextField()),
                ('horario_agendado_inicial', models.DateTimeField()),
                ('horario_agendado_final', models.DateTimeField()),
                ('servico', models.TextField()),
            ],
        ),
    ]
