# Generated by Django 5.2.7 on 2026-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_dias_ocupados_horario_de_desligamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario_de_desligamento',
            name='horario_sempre_ocupado',
        ),
        migrations.AddField(
            model_name='horario_de_desligamento',
            name='horario_sempre_ocupado_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='horario_de_desligamento',
            name='horario_sempre_ocupado_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horarios_agendados',
            name='cliente',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='horarios_agendados',
            name='servico',
            field=models.TextField(max_length=30),
        ),
    ]
