# Generated by Django 5.2.7 on 2026-01-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_remove_horario_de_desligamento_horario_sempre_ocupado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='horario_de_desligamento',
            new_name='horario_de_funcionamento',
        ),
        migrations.RenameField(
            model_name='horario_de_funcionamento',
            old_name='horario_sempre_ocupado_fim',
            new_name='horario_de_funcionamento_fim',
        ),
        migrations.RenameField(
            model_name='horario_de_funcionamento',
            old_name='horario_sempre_ocupado_inicio',
            new_name='horario_de_funcionamento_inicio',
        ),
    ]
