# Generated by Django 5.2.7 on 2026-01-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_rename_horario_de_desligamento_horario_de_funcionamento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dias_ocupados',
            new_name='dias_funcionando',
        ),
        migrations.RenameField(
            model_name='dias_funcionando',
            old_name='dia_ocupado_inteiro',
            new_name='dia_funcionando_inteiro',
        ),
        migrations.RenameField(
            model_name='dias_funcionando',
            old_name='dia_ocupado_metade_fim',
            new_name='dia_funcionando_metade_fim',
        ),
        migrations.RenameField(
            model_name='dias_funcionando',
            old_name='dia_ocupado_metade_inicio',
            new_name='dia_funcionando_metade_inicio',
        ),
    ]
