# Generated by Django 5.2.7 on 2026-01-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_rename_dias_ocupados_dias_funcionando_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dias_ocupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_ocupado_metade_inicio', models.DateTimeField()),
                ('dia_ocupado_metade_fim', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dias_funcionando',
            name='dia_funcionando_metade_fim',
        ),
        migrations.RemoveField(
            model_name='dias_funcionando',
            name='dia_funcionando_metade_inicio',
        ),
    ]
