# Generated by Django 5.2.7 on 2026-01-23 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_dias_ocupado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dias_funcionando',
            new_name='dias_inoperante',
        ),
    ]
